import { NormalizedFamilyTree } from '../types/genealogy';

export const defaultAPIFamilyTree: NormalizedFamilyTree = {
  id: '',
  Firstname: '',
  Middlename: '',
  Lastname: '',
  Gender: '',
  DOB: '',
  Birthplace: '',
  Death: '',
  Deathplace: '',
  Mother: '',
  Father: '',
  Spouse: '',
  Divorced: '',
  BirthplaceCoords: '',
  DeathplaceCoords: '',
  Description: '',
  name: '',
  gender: '',
  parents: [],
  children: [],
  siblings: [],
  spouses: [],
  metadata: {
    profile: [],
    artifacts: [],
    videos: [],
    military: [],
    photos: [],
    miscellaneous: [],
  },
};
